.NET tests show code coverage

diff --git a/.github/workflows/basetests.yml b/.github/workflows/basetests.yml
--- a/.github/workflows/basetests.yml
+++ b/.github/workflows/basetests.yml
@@ -14,6 +14,40 @@ jobs:
       - name: Install dependencies
         run: dotnet restore NET || (ls -lha && exit 1)
       - name: Build
-        run: dotnet build NET --configuration Release --no-restore  --verbosity normal || dotnet build NET --configuration Release --no-restore --verbosity detailed
-      - name: Test
-        run: dotnet test NET --configuration Release --no-restore --verbosity normal || (ls -lha && exit 1)
+      # If built with less verbosity the code generation might fail in a race condition manner
+        run: dotnet build NET --configuration Release --no-restore --verbosity normal || dotnet build NET --configuration Release --no-restore --verbosity detailed
+      - name: Run Tests
+        run: dotnet test NET --configuration Release --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory ./coverage || (ls -lha && exit 1)
+
+      - name: Generate Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        with:
+          name: Test Report
+          path: "**/test-results.trx"
+          reporter: dotnet-trx
+          fail-on-error: true
+
+      - name: Code Coverage Report
+        if: success() || failure()
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: coverage/**/coverage.cobertura.xml
+          badge: true
+          fail_below_min: false
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: false
+          indicators: true
+          output: both
+
+      - name: Write to Job Summary
+        if: success() || failure()
+        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
+
+      - name: Add Coverage PR Comment
+        uses: marocchino/sticky-pull-request-comment@v2
+        if: (success() || failure()) && github.event_name == 'pull_request'
+        with:
+          recreate: true
+          path: code-coverage-results.md
